export const GET_DATA_USERS = "GET_DATA_USERS";
export const GET_DATA_USERS_SUCCESS = "GET_DATA_USERS_SUCCESS";
export const GET_DATA_USERS_PENDDING = "GET_DATA_USERS_PENDDING";

export const ADD_DATA_USERS = "ADD_DATA_USERS";
export const ADD_DATA_USERS_SUCCESS = "ADD_DATA_USERS_SUCCESS";
export const ADD_DATA_USERS_PENDDING = "ADD_DATA_USERS_PENDDING";

export const CREATE_DATA_USERS = "CREATE_DATA_USERS";
export const CREATE_DATA_USERS_SUCCESS = "CREATE_DATA_USERS_SUCCESS";
export const CREATE_DATA_USERS_PENDDING = "CREATE_DATA_USERS_PENDDING";
